GM.Lang = {
    ['CommandNotFound'] = "Такой команды не найдено!",
    ['InvalidAmount'] = "Укажите корректную сумму!",
    ['NotEnoughMoney'] = "У вас недостаточно денег!",
    ['NoPlayerInFront'] = "Перед вами нет игрока!",
    ['CantGiveToSelf'] = "Вы не можете передать деньги самому себе!",
    ['MoneyDropped'] = "Вы выбросили %s$",
    ['MoneyGiven'] = "Вы передали %s$ игроку %s",
    ['MoneyReceived'] = "Игрок %s передал вам %s$",
    ['ToManyMoney'] = "Вы указали слишком большую сумму, лимит до %s$",
    ['InvalidJob'] = "Такой профессии не существует!",
    ['CantBecomeJob'] = "Вы не можете устроиться на эту работу!",
    ['JobChanged'] = "Вы устроились на работу: %s",
    ['ToFastJobChange'] = "Вы недавно заняли данную профессию подождите немного.",
    ['StopCommandSpamming'] = "Прекратите спамить командами!",
    ['NotLookingAtDoor'] = "Вы не смотрите на дверь!",
    ['DoorCantBeOwned'] = "Эту дверь нельзя купить!",
    ['DoorAlreadyOwned'] = "Эта дверь уже кому-то принадлежит!",
    ['DoorReserved'] = "Эта дверь закреплена за организацией!",
    ['DoorCantBuy'] = "Ваша профессия не может покупать двери!",
    ['DoorBought'] = "Вы купили дверь за %s$",
    ['DoorNotYours'] = "Эта дверь вам не принадлежит!",
    ['DoorCantSell'] = "Эту дверь нельзя продать!",
    ['DoorSold'] = "Вы продали дверь за %s$",
    ['DoorsSold'] = "Продано дверей: %s, возвращено %s$",
    ['DoorLimit'] = "Вы не можете владеть более чем %s дверьми!",
    ['DoorNameRequired'] = "Укажите название двери!",
    ['DoorNameTooLong'] = "Название двери не должно быть длиннее %s символов!",
    ['DoorRenamed'] = "Дверь переименована: %s",
    ['DoorNotSubOwner'] = "Вы не совладелец этой двери!",
    ['DoorTargetNotSubOwner'] = "Этот игрок не совладелец этой двери!",
    ['DoorCantAddSelf'] = "Вы не можете добавить в совладельцы самого себя!",
    ['DoorAlreadySubOwner'] = "Этот игрок уже совладелец двери!",
    ['DoorCantAddOwner'] = "Этого игрока нельзя сделать совладельцем двери!",
    ['DoorOwnerAdded'] = "Игрок %s добавлен в совладельцы двери",
    ['DoorOwnerAddedYou'] = "Игрок %s сделал вас совладельцем двери",
    ['DoorOwnerRemoved'] = "Игрок %s удалён из совладельцев двери",
    ['DoorOwnerRemovedYou'] = "Игрок %s забрал у вас совладение дверью",
    ['DoorLeft'] = "Вы больше не совладелец двери",
    ['DoorsLeft'] = "Вы вышли из совладения дверьми: %s",
    ['DoorNoSubOwned'] = "Вы не совладелец ни одной двери!",
    ['LimitHit'] = "Достигнут лимит: %s",
    ['NotYourEntity'] = "Это не ваш объект!",
    ['PropNotAllowed'] = "Этот проп запрещён!",
    ['SalaryReceived'] = "Зарплата: %s$",
    ['VoteYes'] = "За (F1)",
    ['VoteNo'] = "Против (F2)",
    ['VoteSeconds'] = "%s сек",
    ['VoteQueued'] = "В очереди (%s)",
    ['JobVoteRequest'] = "Игрок %s хочет устроиться на работу «%s». Вы за?",
    ['JobVoteRejected'] = "Игроки проголосовали против вашего устройства на работу «%s»!",
    ['JobNoFreeSlots'] = "Свободных мест на этой работе больше не осталось!",
    ['PlayerNotFound'] = "Игрок с таким ID не найден!",
    ['CantDemoteSelf'] = "Вы не можете уволить самого себя!",
    ['CantDemoteJob'] = "С этой профессии нельзя уволить!",
    ['NotEnoughPlayersToDemote'] = "Для увольнения нужно минимум %s игроков на сервере!",
    ['DemoteVoteAlreadyStarted'] = "Голосование за увольнение этого игрока уже идёт!",
    ['DemoteReasonRequired'] = "Укажите причину увольнения!",
    ['DemoteVoteRequest'] = "Игрок %s хочет уволить игрока %s с работы «%s». Причина: %s",
    ['DemoteVoteRejected'] = "Игроки проголосовали против увольнения игрока %s!",
    ['DemoteVoteStarted'] = "Начато голосование за увольнение игрока %s",
    ['Demoted'] = "Вас уволили с работы «%s». Причина: %s",
    ['PlayerDemoted'] = "Игрок %s уволен с работы «%s»",
    ['DeathMoneyLost'] = "Вы потеряли %s$",
    ['DeathRespawn'] = "Возрождение через %s",
    ['DeathPressKey'] = "Нажмите любую клавишу",
    ['DemotedOnDeath'] = "Вы потеряли профессию «%s» после смерти"
}

function roleplay.L(key, ...)
    local text = GAMEMODE.Lang[key] or key

    if (select('#', ...) == 0) then return text end

    return string.format(text, ...)
end
